services:
  - type: web
    name: aibonds
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0 --server.headless true
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: STRIPE_API_KEY
        sync: false
    healthCheckPath: /_stcore/health
