services:
  - type: web
    name: aibonds
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: STRIPE_API_KEY
        sync: false
