# This workflow will test and validate the AI Bonds application on push and PR
name: AI Bonds CI/CD

on:
  push:
    branches: [ main, copilot/** ]
  pull_request:
    branches: [ main ]

jobs:
  test-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test Streamlit app
        run: |
          streamlit run app.py --server.headless true &
          sleep 10
          curl -f http://localhost:8501/?health=check || exit 1
          pkill -f streamlit

  test-nodejs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Node.js dependencies
        run: npm install
      - name: Test Node.js server
        run: |
          npm start &
          sleep 5
          curl -f http://localhost:3000/health || exit 1
          pkill -f node

  deploy-ready:
    needs: [test-python, test-nodejs]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Deployment ready notification
        run: |
          echo "✅ All tests passed! Application is ready for deployment."
          echo "🚀 Deploy using render.yaml for Streamlit or render-nodejs.yaml for Node.js"
